   # Simple RNN(LSTM and GRU) Implementation

In [2]:
# https://deeplearningcourses.com/c/deep-learning-advanced-nlp
from __future__ import print_function, division
from builtins import range, input
# Note: you may need to update your version of future
# sudo pip install -U future

from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

import keras.backend as K
if len(K.tensorflow_backend._get_available_gpus()) > 0:
  from keras.layers import CuDNNLSTM as LSTM
  from keras.layers import CuDNNGRU as GRU


T = 8 # Sequence length
D = 2 # Input Dimensionality
M = 3 # Hidden Layer size 


X = np.random.randn(1, T, D)


def lstm1():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)


def lstm2():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences=True)
  # rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)


def gru1():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)


def gru2():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)



# print("lstm1:")
# lstm1()
# print("lstm2:")
# lstm2()
# print("gru1:")
# gru1()
# print("gru2:")
# gru2()



In [3]:
print("lstm1:") # By default the return_state = True # Considers only one output that is the last output
lstm1()
print("lstm2:") # return_sequence = True # It considers every output
lstm2()

lstm1:
o: [[ 0.3217187   0.16237344 -0.36327904]]
h: [[ 0.3217187   0.16237344 -0.36327904]]
c: [[ 0.675547    0.29899424 -0.7674577 ]]
lstm2:
o: [[[ 5.78418113e-02 -6.72095492e-02 -4.74597327e-02]
  [ 2.80481428e-01 -1.01390183e-01 -5.11641428e-02]
  [ 1.69834509e-01 -5.98019622e-02  3.80781894e-05]
  [ 5.89486808e-02 -7.51858875e-02 -2.35811919e-02]
  [-4.56871418e-03 -4.05552015e-02 -7.17352005e-03]
  [-5.73910773e-02  7.33386800e-02  4.98028956e-02]
  [-1.05796196e-01  9.82574821e-02  3.89654823e-02]
  [-8.82705152e-02  4.71285172e-03 -2.36340966e-02]]]
h: [[-0.08827052  0.00471285 -0.0236341 ]]
c: [[-0.3288231   0.0105776  -0.03433786]]


In [4]:
print("gru1:") # By default the return_state = True  # Considers only one output that is the last output
gru1()
print("gru2:") # return_sequence = True # It considers every output
gru2()

gru1:
o: [[0.48059177 0.06008199 0.5174747 ]]
h: [[0.48059177 0.06008199 0.5174747 ]]
gru2:
o: [[[ 0.00753734 -0.2082217   0.43133575]
  [-0.32994342 -0.14123373  0.59990114]
  [-0.07048532  0.03102256  0.13565029]
  [ 0.21792118 -0.03484058  0.16097349]
  [ 0.37275943  0.01243955 -0.04795794]
  [ 0.44832247  0.06870154 -0.2834326 ]
  [ 0.5122981   0.07244074 -0.38289058]
  [ 0.6593656  -0.20818871  0.2791289 ]]]
h: [[ 0.6593656  -0.20818871  0.2791289 ]]
